---
title: "Rough Draft"
author: "David Chen"
date: "5/2/2020"
output: html_document
---

Rough Draft




# Introduction

Vaccines have proven an effective way to protect people against certain viral diseases, but not everyone gets the vaccines that are available.  There are some legitimate reasons people cannot get a vaccine (e.g. compromised immunity or allergy to an ingredient) that cannot be overcome, but other people avoid vaccines without these reasons.

This data for this project comes from a contest hosted by DrivenData.  The goal of the contest is to predict how likely individuals are to receive two vaccines: the H1N1 and seasonal flu.  The data was collected through the National 2009 H1N1 Flu Survey.  A number of belief, behavior, and demographic factors were collected and used to create models to predict whether the individual received one, both, or neither of the vaccines.


+ Why we took on the project
+ What we're trying to solve 



## EDA 





### Clustering



# Analyses

## Splitting into training/testing


## Naive Model 




## Model 1 - Logistic / QDA

+ Mention how the model works, why we picked the model

+ Why we're doing certain steps (Cross validation)

+ Considerations while fitting (conditions are met)

+ Test/train results, confusion matrix + accuracy + specificity/sensitivity


+ Keep in mind model specific subjects (pruning)


## Model 2 - Tree-based




## Model 3 - SVM




## Comparing them all together

+ Full table of the results

-> Just testing accuracy/spec/sens 


# Conclusion 
















